name: Lint

on: [pull_request]

jobs:
    build:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'
                  cache: pnpm
            - run: pnpm install
            - run: pnpm run lint
